### ISSUE TITLE
snaps for Linux

### ISSUE THREAD

**Issue by antonpaisov** [phrase/phraseapp-client#101]
hey there,
I wonder if you have considered packaging the CLI app in a snap and distributing it via https://snapcraft.io/?
would be really cool to have a homebrew-ish way of installing it on Linux :)

**Comment by sacry-dyn** [comment]
Hi @antonpaisov thank you for reaching out. We will discuss this and come back to you! Definitely considering it, though there a few things that we might do first (regarding the client).

**Comment by tobstarr** [comment]
Hi @antonpaisov. Providing snaps is a good idea but currently not on our roadmap. I will close this issue for the time being and reopen it when things change on our end.

**Comment by antonpaisov** [comment]
@tobstarr, @sacry-dyn sure! I'll try to submit a PR with a yml for snapcraft when I have time, so you'll be the owners of that snap (I believe configuration there is quite simple)
