### ISSUE TITLE
Add download link for latest release

### ISSUE THREAD

**Issue by delolmo** [phrase/phraseapp-client#105]
Could you create a download link for the latest release of the API client? 

E.g. "https://github.com/phrase/phraseapp-client/releases/download/latest/phraseapp_linux_386"

I am trying to deploy server instances automatically in Amazon Web Services and it would be useful to be able to use the wget command without knowing the version number.

**Comment by tobstarr** [comment]
Hi,

I don't think github provides an option to create a symlink to the most recent release but you could use a simple script like this:

```
curl -s https://api.github.com/repos/phrase/phraseapp-client/releases | jq '.[0] | .assets[] | select(.name == "phraseapp_linux_386") | .browser_download_url' -c -r
```
to get the most recent download url. You would need to install jq (https://stedolan.github.io/jq/) on your servers though.

I still recommend to use a specific version number as we might change the interface of the CLI tool some time in the future (and then bump the version to 2.x) which would then probably break your server side code.
