### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by argon** [phrase/phraseapp-client#11]
The previous CLI tool was great because it could be installed as a gem with our project bootstrapping scripts. The only way to do that with this new tool is if the go toolchain is installed, using `go get`. Even then it installs with a different name than your documentation recommends. (`phraseapp-client` vs `phraseapp`). This tool would be much more pleasant to use with a homebrew formula

```
$ brew install phraseapp
```

Are there plans for this?

**Comment by docstun** [comment]
We're already working on it :) You can help us by starring the repository since repos require a certain popularity in order to be added to homebrew.

**Comment by argon** [comment]
A homebrew tap would be a great temporary solution :+1:

**Comment by argon** [comment]
This works for me, for now https://github.com/argon/homebrew-phraseapp/blob/master/phraseapp.rb.

```
$ brew tap argon/phraseapp
$ brew install phraseapp
```

**Comment by fredv** [comment]
Hi @argon,
thank you for suggesting this! We published the recipe now under our new homebrew tap repo:

```
$ brew tap phrase/brewed
$ brew install phraseapp
```

Best,
Frederik

**Comment by argon** [comment]
Great! The only problem is that the instructions in the readme for the tap are outdated. To be correct, it should be

> Add tap to your local homebrew installation:
>
>     brew tap phrase/brewed
> Install phraseapp client:
>
>     brew install phrase/brewed/phraseapp

Also `brew install phraseapp` works perfectly well, it doesn't really need the extra components in the path.
