### ISSUE TITLE
Crash when GitHub is down

### ISSUE THREAD

**Issue by ddfreyne** [phrase/phraseapp-client#112]
Running `phraseapp pull` when GitHub is down yields the following:

```
ERROR: This should not have happened: runtime error: invalid memory address or nil pointer dereference - Contact support: support@phraseapp.com
```

Naïve thought: Could it be that the response’s HTTP status code is not verified when checking whether or not this release is the most recent? If it’s 5xx, it might still try to fetch the version from the response body and end up with null, hence the error?

**Comment by tobstarr** [comment]
@ddfreyne thank you for reporting the issue. We will fix this in our next release

**Comment by tobstarr** [comment]
@ddfreyne could you please provide us with the output of
```
$ ~/bin/phraseapp-client info
Built at:                            2017-11-13T14:35:23Z
PhraseApp Client version:            1.6.0
PhraseApp Client revision:           fc02148d7a3a3fac8333fbb14142558c144e0d4a
PhraseApp Library revision:          92f39643e2ed06e74b507f48b5c08ea699085d4c
PhraseApp Docs revision client:
PhraseApp Docs revision lib:
PhraseApp Generator revision client:
PhraseApp Generator revision lib:
GoVersion:                           go1.8.3
```
We received some panic backtraces yesterday but those are from an outdated client.

**Comment by ddfreyne** [comment]
We were running an older version (1.4.0 < 1.6.0), and upgrading it made the problem disappear. Apologies!

`github.com` being unavailable no longer causes a panic:

```
ERROR: dial tcp 127.0.0.1:443: getsockopt: connection refused
ERROR: no targets for download specified
```

I’ll close this issue!

**Comment by tobstarr** [comment]
:+1:
