### ISSUE TITLE
Missing a macOS installer package

### ISSUE THREAD

**Issue by MiMo42** [phrase/phraseapp-client#114]
You should really provide an installer package on macOS.
*.dms and *.tar files are uncommon with macOS. 
You should provide releases in common file formats like dmg, pkg, zip.
An installer would be great.

brew install works though.

**Comment by theSoenke** [comment]
Hi, sorry for our late response on this issue. Do you still have any use for a MacOS installer? In comparison simply using brew has quite a few advantages like for example the update mechanism

**Comment by theSoenke** [comment]
Currently we have no plans to provide a Mac installer. We might reconsider this in the future though
