### ISSUE TITLE
Releases do not work with alpine

### ISSUE THREAD

**Issue by Byron-TW** [phrase/phraseapp-client#115]
The current releases seem to be built for debian, which makes it impossible to use them with alpine.
A possible solution is to provide MUSL builds instead, which produces a binary running on all moderately modern linux kernels.

### How to reproduce

```bash
docker run -it alpine
/ # apk -U add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20171114-r0)
(2/4) Installing libssh2 (1.8.0-r2)
(3/4) Installing libcurl (7.58.0-r1)
(4/4) Installing curl (7.58.0-r1)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 6 MiB in 15 packages
/ # curl -L https://github.com/phrase/phraseapp-client/releases/download/1.6.0/phraseapp_linux_amd64.tar.gz  | tar -zxv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   618    0   618    0     0   1190      0 --:--:-- --:--:-- --:--:--  1190
  0 2685k    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0phraseapp_linux_amd64
100 2685k  100 2685k    0     0   832k      0  0:00:03  0:00:03 --:--:-- 1226k
/ # ./phraseapp_linux_amd64
/bin/sh: ./phraseapp_linux_amd64: not found
/ # ldd phraseapp_linux_amd64
        /lib64/ld-linux-x86-64.so.2 (0x7f7db910e000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7db910e000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7db910e000)
/ #
```

**Comment by theSoenke** [comment]
Hi @Byron-TW thanks for reporting it. As a quick workaround you could build the client from source to ensure that MUSL is used. With go installed you can build it simply by running `go build`. Would this work for you?

**Comment by Byron-TW** [comment]
Thanks, this will certainly work. Yet I encourage you to either cross-compile for all the linuxes out there, or just provide a single MUSL binary to catch them all.
This makes it much easier to use it within build environments for example.

**Comment by theSoenke** [comment]
Thanks for the feedback. For the next release we will try to provide a binary that also works on alpine. The solution might already be to disable CGO
`CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' `

**Comment by Byron-TW** [comment]
Great to hear, thank you! Indeed, doing it like this is the Golang way, I
was still thinking Rust-lang for some reason :D!

**Comment by theSoenke** [comment]
The latest release [1.6.1](https://github.com/phrase/phraseapp-client/releases/tag/1.6.1) now should be fully static and not rely on any C standard library

**Comment by francois2metz** [comment]
Thanks for fixing this. I updated my dockerfile to remove the workaround around this. https://github.com/francois2metz/phraseapp-docker
