### ISSUE TITLE
Support Rate Limiting & Retry

### ISSUE THREAD

**Issue by gbrehmer** [phrase/phraseapp-client#116]
We have a lot of files to upload because we split up each ui module/page/functionality in a seperate files. We can not upload all files at once. Currently we receive HTTP 502 Bad Gateway or rate limiting errors.

**Comment by theSoenke** [comment]
Hi @gbrehmer, could you write us a short message over our [contact page](https://phraseapp.com/contact)?  Then we will try to find a solution for this. Thanks

**Comment by dragosv** [comment]
This also happens to me as well when uploading many files. I am getting 502 HTTP 502 Bad Gateway all the time

**Comment by theSoenke** [comment]
@dragosv We resolved an issue today which resulting in an increased number of 502 status codes. Please let me know if you should still see this issue

**Comment by dragosv** [comment]
Works now.
