### ISSUE TITLE
Globbing source files (e.g. ./config/locales/views/**/*.yml) isn't working for me in Linux

### ISSUE THREAD

**Issue by fredv** [phrase/phraseapp-client#13]
Looks like this could be fixed in 639: https://github.com/phrase/phraseapp-client/blob/master/push.go

Globbing source files (e.g. ./config/locales/views/**/*.yml) isn't working in Linux. Here's the stack trace:

panic: regexp: Compile(`*.yml`): error parsing regexp: missing argument to repetition operator: `*`

goroutine 1 [running]:
regexp.MustCompile(0xc2081c1709, 0x5, 0xc2082d26f0)
/usr/local/Cellar/go/1.4.2/libexec/src/regexp/regexp.go:221 +0x15a
main.(*Parser).TagMatches(0xc2082a9290, 0xc2081c1709, 0x5, 0x1)
/go/src/github.com/phrase/phraseapp-client/push.go:619 +0x63
main.(*Parser).Eval(0xc2082a9290, 0xc2080b43fa, 0x5, 0x1)
/go/src/github.com/phrase/phraseapp-client/push.go:605 +0x2e2
main.(*Source).FindTaggedMatches(0xc2080a7380, 0xc20809ad80, 0x27, 0x200)
/go/src/github.com/phrase/phraseapp-client/push.go:535 +0x363
main.(*Source).generateLocaleForFile(0xc2080a7380, 0xc20809ad80, 0x27, 0xc2080dd290, 0x0, 0x0)
/go/src/github.com/phrase/phraseapp-client/push.go:233 +0x65
main.(*Source).LocaleFiles(0xc2080a7380, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/phrase/phraseapp-client/push.go:222 +0x6b4
main.(*Source).Push(0xc2080a7380, 0xc2080aaa40, 0x0, 0x0)
/go/src/github.com/phrase/phraseapp-client/push.go:85 +0x19d
main.(*PushCommand).Run(0xc2080a7000, 0x0, 0x0)
/go/src/github.com/phrase/phraseapp-client/push.go:35 +0x193

**Comment by fredv** [comment]
@sacry-dyn solved and tested in 1.0.1 ?

**Comment by sacry-dyn** [comment]
@fredv was tested on a VM and worked
