### ISSUE TITLE
Error when pulling update

### ISSUE THREAD

**Issue by Alexey-Matjuk** [phrase/phraseapp-client#141]
Today started receiving an error when pulling update (yesterday worked):
```
$ phraseapp pull
ERROR: dial tcp: lookup github.com on 82.209.243.241:53: write udp 192.168.100.6:52590->82.209.243.241:53: write: host is down
ERROR: Get https://api.phraseapp.com/v2/projects/xxx/locales?page=1&per_page=25: dial tcp: lookup api.phraseapp.com on 82.209.243.241:53: write udp 192.168.100.6:61931->82.209.243.241:53: write: host is down
```
phraseapp client version is 1.8.0
macOS Mojave 10.14 Beta (18A365a)

**Comment by theSoenke** [comment]
Hi @Alexey-Matjuk, could you try whether you can reach the host with `ping api.phraseapp.com` to make sure that a network connection is possible?

**Comment by Alexey-Matjuk** [comment]
```
$ ping api.phraseapp.com
PING api.phraseapp.com (54.77.119.248): 56 data bytes
64 bytes from 54.77.119.248: icmp_seq=0 ttl=233 time=62.316 ms
64 bytes from 54.77.119.248: icmp_seq=1 ttl=233 time=52.182 ms
...
```

**Comment by Alexey-Matjuk** [comment]
I just generated new token and tried
```
curl -X GET \
  https://api.phraseapp.com/api/v2/projects \
  -H 'Authorization: Bearer MY_TOKEN' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: b2a74fab-1455-445a-bd9c-3591dc905d44'
```
And received *401 Unauthorized*. But with basic authentication I'm able to receive valid JSON response.

**Comment by Alexey-Matjuk** [comment]
I used wrong token Authentication in may last comment. But don't know if correct one was working or not. Because today client also started working and I'm closing this issue

**Comment by theSoenke** [comment]
Thanks for the confirmation that it now works. Feel free to contact us anytime if anything should not work as expected
