### ISSUE TITLE
Windows installer is outdated

### ISSUE THREAD

**Issue by igodorogea** [phrase/phraseapp-client#145]
Installer downloaded from here https://github.com/phrase/phraseapp-client/releases/download/1.9.4/phraseapp_windows_setup.exe
is not latest version(1.9.4) but 1.7.4

**Comment by theSoenke** [comment]
Thanks for reporting it. This will be fixed in the next release

**Comment by theSoenke** [comment]
The Windows installer in the latest release 1.10.0 should now also contain the correct version number: https://github.com/phrase/phraseapp-client/releases/tag/1.10.0
