### ISSUE TITLE
Inconsistent locale generation

### ISSUE THREAD

**Issue by iamandrewluca** [phrase/phraseapp-client#149]
> This issue I also reported to online support chat

We are using TYPO3 CMS that uses `xlif` localisation files
In this file you have to indicate `source-language` and `target-language`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file original="global" datatype="plaintext" source-language="en" target-language="en">
    <body>
        ...
    </body>
  </file>
</xliff>
```

In PhraseApp dashboard I have a `default locale` with
Name: `English` and Locale: `English - en`
I push file showed above through `cli`.
In PhraseApp a new locale is created with
Name: `en` and Locale: `English - en`
And it seems is based on `source-language` from file

But when I pull.
My default locale from PhraseApp, with Name: `English` creates same file
With `source-language` set to `en`

If I set `source-language` to `English` and push.
No new locale is created. Locale with name `English` is used.
On pull `source-language` is also set to `en`
On next push a new locale is created with
Name: `en` and Locale: `English - en`

Only solution right now is to give names using locale code ([rfc5646](https://tools.ietf.org/html/rfc5646))

**Comment by theSoenke** [comment]
Thanks for reporting this. This behavior is generally related to our upload and download behavior an not client specific. I forwarded you to our support team to resolve this
