### ISSUE TITLE
Error when running pull command

### ISSUE THREAD

**Issue by gcoderre** [phrase/phraseapp-client#17]
On a clean install of phraseapp through homebrew:

```
ERROR: parse https://api.phraseapp.com/v2/projects/<%= ENV["PHRASEAPP_PROJECT_ID"] %>/locales: invalid URL escape "%= "
```

**Comment by gcoderre** [comment]
Well nevermind that issue. :) I'm so used to using yaml with Ruby that I plunked ERB in there and expected it to work.

Can I interpolate environment variables somehow?

**Comment by docstun** [comment]
@gcoderre you should store these things in your `.phraseapp.yml` config file. For the access token, we already support putting it into the ENV: http://docs.phraseapp.com/developers/cli/usage/

**Comment by gcoderre** [comment]
Sorry, I didn't read the documentation properly. That fixes it. Thanks @docstun.
