### ISSUE TITLE
[Request] Support Symfony locale code format

### ISSUE THREAD

**Issue by sylfabre** [phrase/phraseapp-client#179]
I am using Symfony where locale code is using this format `fr_FR`

But using the client, `<locale_code>` gives this format `fr-FR`

Please add a way to support ISO/IEC 15897 like `<locale_code_iso>` giving `fr_FR`

Some context on Symfony repo: https://github.com/symfony/symfony/issues/28150

**Comment by theSoenke** [comment]
Hi @sylfabre, a possible solution would be to use `<locale_name>` instead as a placeholder. This way you have full control over the name of the locale

**Comment by sylfabre** [comment]
@theSoenke thanks. You may add this to your doc :)

**Comment by theSoenke** [comment]
Great to hear that this already helped. I will have a look how we can make this a bit more prominent in the docs :)
