### ISSUE TITLE
Misleading rate limit error

### ISSUE THREAD

**Issue by Arjan-Zuidema** [phrase/phraseapp-client#182]
Sometimes I get this in stderr:

```
Error: Command failed: phraseapp keys list --locale-id xxx -q translated:false
ERROR: Rate limit exceeded: from 500 requests 492 are remaining (reset in 201 seconds)
```

This should not occur when there are 492 remaining of the 500, or it should always be outputted so it can be parsed and ignored if needed

**Comment by theSoenke** [comment]
Hi, thanks for reporting this. This is indeed misleading and I will have a look why this is reported incorrectly

**Comment by theSoenke** [comment]
@Arjan-Zuidema We released  a new CLI v2 https://github.com/phrase/phrase-cli which should resolve this issue
