### ISSUE TITLE
Xcode 11.2 support missing

### ISSUE THREAD

**Issue by L-Delejon** [phrase/phraseapp-client#187]
Hello,

You have to compile your SDK with Swift 5.1.2 and release it.

Best regards
Leo

**Comment by theSoenke** [comment]
Hi @L-Delejon, this should have been addressed in the latest release: https://github.com/phrase/ios-sdk/releases/tag/1.2.2

**Comment by L-Delejon** [comment]
Ah we see now, thank you!
