### ISSUE TITLE
Fusion two projects

### ISSUE THREAD

**Issue by chemitaxis** [phrase/phraseapp-client#188]
Hi team, we have two API projects that are currently two different projects in Phraseapp. We are in this moment migrating the two projects to one project, how can I combine / fusion the old projects to one new project on phraseapp? Thanks!

**Comment by theSoenke** [comment]
Hi, this issue might go a bit beyond the scope of the client. Could you contact us via the chat on the website or at https://phrase.com/contact to discuss this?

**Comment by chemitaxis** [comment]
Ok, I will... thanks!
