### ISSUE TITLE
Provide official docker image

### ISSUE THREAD

**Issue by tenjaa** [phrase/phraseapp-client#191]
Hey,
have you thought about providing an official docker image?
We are using one for CI/CD but have to patch it from time to.
Of course everyone has different needs what needs to be in there, but updating based on a docker image is probably easier than everyone building their own.

In our case for example we would use it to automatically update translations once per week. So quickly installing jq during runtime or similar wouldnt even be a problem for us and therefore we would be happy with a small image only containing the phraseapp cli.

See also:
https://github.com/francois2metz/phraseapp-docker/blob/master/Dockerfile
https://github.com/tenjaa/phraseapp-docker/blob/master/Dockerfile

**Comment by theSoenke** [comment]
Hi @tenjaa, we've actually also discussed this internally before. We did not get around to publish a Docker image yet, but I will let you now as soon it should be available

**Comment by theSoenke** [comment]
Issue is being tracked for CLI v2 in https://github.com/phrase/phrase-cli/issues/13
