### ISSUE TITLE
Pass project id as command-line argument for pulling and pushing

### ISSUE THREAD

**Issue by learnitmyway** [phrase/phraseapp-client#200]
Is it possible to something like `phraseapp pull --project-id $PHRASE_PROJECT_ID`. I would like to avoid checking in the project id into version control because this doesn't seem like the right thing to do.

**Comment by theSoenke** [comment]
Hi @learnitmyway, this is currently not possible. A config file can also contain multiple project ids. May I ask why you want to not check in the project id into version control? This is not a secret and is only a randomly generated identifier

**Comment by learnitmyway** [comment]
Hmm I guess I was thinking of it more as a secret. If a bad actor had the
project id they would only have to guess the access token. If they didn't
have the project id, wouldn't they have to guess both?

**Comment by rlisowski** [comment]
If someone has your access token then can simply list your projects and see all project ids.

**Comment by theSoenke** [comment]
In any case an attacker has to guess the access token. Knowing the project id does not provide an advantage to a bad actor

**Comment by learnitmyway** [comment]
True! This helped, thank you!!
