### ISSUE TITLE
[doc] is phrase.yml only used for push/pull operations? 

### ISSUE THREAD

**Issue by misterfresh** [phrase/phraseapp-client#203]
I added to the command "phrase translations list" the "--config" flag with a path to a phrase.yml file that contains the project_id variable.
But when I run that command I still get an error and am asked to provide the project_id.
So is the phrase.yml only used for push pull operations, and all other operations require the project_id to be provided in a flag?
Second question: when using the config flag and a phrase.yml file, is it possible to remove the access token information from the phrase.yml and provide it as a flag instead?
Thanks for your help, I searched the phrase app documentation and through google but could not find that information.

**Comment by rlisowski** [comment]
This is a question about CLI v2, it's repo is here https://github.com/phrase/phrase-cli. Sorry for the confusion, I will add info about it to the readme.

To answer your questions:
1. yes, for now, the project_id from config file is used only in pull/push/cleanup commands phrase/phrase-cli#16
2. you can remove access token from file and provide it via flag or overwrite it with the --access_token flag. We will update https://help.phrase.com/help/usage to reflect that info.

**Comment by rlisowski** [comment]
@misterfresh please let me know if I answered your questions and we can close this issue.

**Comment by misterfresh** [comment]
Hello @rlisowski , thanks for your help. Yes we can close the issue.
