### ISSUE TITLE
Error on push: "failed to create locale: no locale code specified"

### ISSUE THREAD

**Issue by andreasknoepfle** [phrase/phraseapp-client#28]
I got an app with multiple "yml" files that should be treated seperatly. I have a configuration, that works perfectly fine for us.
But the "push" still shows **"failed to create locale: no locale code specified"** for each of the additional yml files, but not the default one. Its a Ruby on Rails project if this matters anyhow.

Is this a bug in phraseapp or is something wrong with my configuration and it only works by accident ?

phraseapp push
> Uploading config/locales/de.yml
> Uploaded config/locales/de.yml successfully.
> Uploading config/locales/devise.de.yml
> **failed to create locale: no locale code specified**
> Uploading config/locales/devise.en.yml
> **failed to create locale: no locale code specified**
> Uploading config/locales/devise.views.de.yml
> **failed to create locale: no locale code specified**
> Uploading config/locales/devise.views.en.yml
> **failed to create locale: no locale code specified**
> Uploading config/locales/en.yml
> Uploaded config/locales/en.yml successfully.
> 

.phraseapp.yml
```
phraseapp:
	    access_token: XXX
	    project_id: XXX	   
	    file_format: yml
	    push:
	      sources:
	        -
	          file: ./config/locales/<locale_name>.yml
	          params:
	            tags: ".yml"
	        # devise
	        -
	          file: ./config/locales/devise.<locale_name>.yml
	          params:
	            tags: "devise.yml"
	        # devise.views
	        -
	          file: ./config/locales/devise.views.<locale_name>.yml
	          params:
	            tags: "devise.views.yml"
	    pull:
	      targets:
	         # default
	        -
	          file: ./config/locales/<locale_name>.yml
	          params:
	            tag: ".yml"
	        # devise
	        -
	          file: ./config/locales/devise.<locale_name>.yml
	          params:
	            tag: "devise.yml"
	        # devise.views
	        -
	          file: ./config/locales/devise.views.<locale_name>.yml
	          params:
	            tag: "devise.views.yml"
```

**Comment by gfrey** [comment]
Hi @andreasknoepfle,
that's a tough one. The problem is that the a file `/devise.views.en.yml` would match `/<locale_name>.yml

**Comment by andreasknoepfle** [comment]
Thanks. Now the errors finally make some sense to me :).

Best regards,
Andi
