### ISSUE TITLE
Return code sometimes is zero when an error is encountered

### ISSUE THREAD

**Issue by rubenvdb** [phrase/phraseapp-client#3]
When the phraseapp cli tool encounters an error, "ERROR" is shown in the output, but the return code of the process is 0. When using the tool in an automated environment, scripts and CI tools (e.g. Jenkins) rely on this return code to determine whether the action succeeded.

Steps to reproduce:
- remove the access token from the .phraseapp.yml
- execute "phraseapp pull/push"
  > output: ERROR: either username or token must be given
- execute "echo $?"
  > output: 0
  > expected output: 1

**Comment by fredv** [comment]
Thanks for noting this behavior, @rubenvdb. We'll look into how to solve this more conveniently.

**Comment by sacry-dyn** [comment]
@rubenvdb this should be fixed. We will have to release a new version though. Expect it to happen today.

**Comment by sacry-dyn** [comment]
@rubenvdb I will close this, the latest release 0.3.1.beta should return 1 if an error occured. If anything pops up feel free to reopen.
