### ISSUE TITLE
Config file as a parameter

### ISSUE THREAD

**Issue by floskel** [phrase/phraseapp-client#30]
Is it possible to specify what config file to use? 
Something like `phraseapp pull --config=.my_phrasapp_config.yml`

**Comment by sacry-dyn** [comment]
@floskel We have thought about it as well but had to sort out a few things before. I think this is a reasonable option which we should add in a near future release, what do you think @tobstarr ?

**Comment by docstun** [comment]
@floskel did you try using the `PHRASEAPP_CONFIG ` environment variable? See the documentation here: https://phraseapp.com/docs/developers/cli/configuration/

**Comment by sacry-dyn** [comment]
@floskel I will close the Issue for now. If you want to reopen, feel free to do so.
