### ISSUE TITLE
Placeholder Android xml format

### ISSUE THREAD

**Issue by vinzen** [phrase/phraseapp-client#32]
Having an iOS project, `%@` is correctly converted to `%s`.
But when there is multiple placeholder in the same translation, It should not be `%s` but `%1$s`, `%2$s` etc

See http://developer.android.com/intl/es/guide/topics/resources/string-resource.html#FormattingAndStyling

**Comment by docstun** [comment]
Thanks for sharing this. It looks like an issue with our API, not with the client so I will close this issue here and keep you updated via our support team.

**Comment by sdurovich** [comment]
@docstun 
Are there any updates regarding this issue? We faced with the same problem.

**Comment by theSoenke** [comment]
Hi @sdurovich, unfortunately this has not been addressed in the API yet. I will look into it and let you know as soon as I have an update

**Comment by sdurovich** [comment]
Hi @theSoenke 
Do you have any news?

**Comment by theSoenke** [comment]
@sdurovich Unfortunately not yet. I hope that we can tackle this very soon. This is one of the next tasks on my list

**Comment by theSoenke** [comment]
@sdurovich Is there a specific reason why you are using multiple `%@` placeholders instead of positional placeholders like `%1$@` on iOS? This would have the advantage that the placeholder is language independent. For example when one placeholder would be in a different position in some languages

**Comment by phcannessondkt** [comment]
Hey guys, any update on this ?

**Comment by theSoenke** [comment]
Hi @phcannessondkt, if you are using multiple placeholders I would highly recommend to use positional placeholders. This will solve the issue and also provide a guarantee that the order of the placeholders is still correct in translations. Let me know if that should not be possible in your case
