### ISSUE TITLE
Phrase push doesn't support "tags"

### ISSUE THREAD

**Issue by rubenvdb** [phrase/phraseapp-client#4]
The old CLI tool allowed you to pass a "--tags" argument to add tags to translations pushed with this parameter.

Expected behavior:

    phraseapp push --tags=foo,bar

Attaches one or multiple tags with your file upload. All keys added by the push will be tagged with the specified tags.

**Comment by fredv** [comment]
Hi @rubenvdb, this is correct. Please use the new functionality `phraseapp upload create` for this as described here: http://docs.phraseapp.com/api/v2/uploads/
Best, Frederik

**Comment by sacry-dyn** [comment]
Hi @rubenvdb, as @fredv noted this is correct. If you want to see what arguments are supported do `phraseapp push --help`. `push / pull / init` are special commands that solely rely on a `.phraseapp.yml`. If you would like to upload locales and use `--tags` as an option, use `phraseapp upload create`. See here for more information on push/pull:

http://docs.phraseapp.com/guides/working-with-phraseapp/command-line-client/

If that fixes the issue for you I would like to close it.

Regards,
Matthias

**Comment by rubenvdb** [comment]
Hi @sacry-dyn ,

Although I understand the use of the upload command, I still can see benefit in the possibility of adding an additional tag when pushing new keys. We used the tags flag to add a tag containing the git sha1 of the commit in which the keys were added. In complex syncing situations, the push command is easier to use (because it reads the config from the file).
That being said, I would understand you closing this issue because it is an exceptional use case.

**Comment by sacry-dyn** [comment]
Hi @rubenvdb 

we will keep the request in mind though. We want to offer as many options as possible. push and pull however can easily take 8+ command line arguments so to keep it simple we restrain from adding cmd arguments for now. If the need arises we are certainly open to consider a few command line options that enhance the interactive experience like tags or update_translations.

**Comment by j4zz** [comment]
I’m sorry, but what would be the `pull` equivalent for only pulling translations for certain tags only? With the deprecated [phrase gem](https://github.com/phrase/phrase), this would have been `phrase pull de --tag=feature-messenger-v2` for example. 

This was probably referred to by @sacry-dyn [here](https://github.com/phrase/phraseapp-client/issues/4#issuecomment-127212451), but the link referred 404s. It’s probably good to have it answered here in the issue, anyways.

**Comment by fredv** [comment]
Hi @j4zz, there is a new command, called "phraseapp upload create" which supports tags. Also, inside a push source, you can specify the same params upload create takes for the source file you're trying to tag - if this is supposed to happen on every push. For singular import, use upload create, for regular pushes add the params as described here: http://docs.phraseapp.com/developers/cli/configuration/

Example:
    push:
      - 
        file: "en.feature.yml"
        params:
          tags: "feature,other-tag"
