### ISSUE TITLE
Bad link to the documentation

### ISSUE THREAD

**Issue by lborie** [phrase/phraseapp-client#40]
In the file [shared.go](https://github.com/lborie/phraseapp-client/blob/master/shared.go#L42), the link to the documentation is wrong in the file extension management.

It should be : 
`http://docs.phraseapp.com/docs/guides/formats/%s`

**Comment by sacry-dyn** [comment]
@lborie thank you for noticing. We will fix it and release it as soon as possible.

**Comment by lborie** [comment]
Sure, you're right !. The good URL is 
`https://phraseapp.com/docs/guides/formats/%s`

:+1:

**Comment by sacry-dyn** [comment]
We fixed the link in this commit (and a couple of other urls as well):

https://github.com/phrase/phraseapp-client/commit/769a42be9940488d47ca963283061aa646979fc9

A new release will be available soon.

**Comment by sacry-dyn** [comment]
@lborie fixed and released in https://github.com/phrase/phraseapp-client/releases/tag/1.1.18
