### ISSUE TITLE
Delete translation by key

### ISSUE THREAD

**Issue by vanniktech** [phrase/phraseapp-client#44]
Is there any way to delete a translation from the CLI by a key?

Let's imagine I have the key `cancel` and I want to delete it in all locales on a given project, how would you do that with the CLI?

**Comment by sacry-dyn** [comment]
You would use the key#destroy action:

https://phraseapp.com/docs/api/v2/keys/#destroy

e.g.

`phraseapp key delete <project_id> <key_id>`

You can get the `id` by either going to the key in the Translation Center or by searching the keys via

https://phraseapp.com/docs/api/v2/keys/#search

e.g.

`phraseapp keys search <project_id> --query 'mykey*' `

Does this answer your question?

**Comment by vanniktech** [comment]
Wow that's amazing and yes it does. Thank you also for the fast reply.  Feel free to close this one.

**Comment by sacry-dyn** [comment]
@vanniktech Great! 👍
