### ISSUE TITLE
Client doesnt update translator notes

### ISSUE THREAD

**Issue by bdorfman** [phrase/phraseapp-client#47]
I'm using the phraseapp command line client to upload .strings files generated from an iOS Xcode project to Phrase. However, it doesn't seem to update any translator notes that changed, and as such there are now a bunch of strings in our Phrase project that incorrectly say "No comment provided by developer". I have `update_translations: true` set in my yaml file.

**Comment by sacry-dyn** [comment]
Hi, this is an issue that is not connected to the client. We currently do not update descriptions on key updates, only on key creation or if you manually edit them in PhraseApp. We will think about possible solutions to this, as this is currently not possible to edit them directly via API. The only possibility I see is that you grep key_name and description and match it with the keys in the API via keys endpoint and update the keys accordingly.

**Comment by bdorfman** [comment]
This seems like a fairly major problem, as accurate developers notes are essential to the translation process. Manually duplicating all our note edits one at a time in the web interface is not really a practical replacement for this functionality.

**Comment by sacry-dyn** [comment]
We will look into it and think about possible solutions that do not break existing behaviour. We can keep this issue open and resolve it when we find possible solutions. However we cannot change anything about the PhraseApp Client that could deal with this issue.

**Comment by bdorfman** [comment]
Any update on this? It is making it extremely frustrating to use with an iOS project, and I assume other people trying to use Phrase with the iOS apps are having similar issues. If it is a Phrase API issue and you somehow cannot communicate internally in the company, is there somewhere else I should post this issue so the API team can see it?

**Comment by sacry-dyn** [comment]
Hi, the problem was already communicated and we are going to resolve this in the near future. We will probably go with an approach where you set an extra option `--update-descriptions=true` and the descriptions will be overwritten with the local ones.

**Comment by sacry-dyn** [comment]
@bdorfman we added the possibility to update-descriptions via form and API. The latest phraseapp-client: https://github.com/phrase/phraseapp-client/releases/tag/1.2.3

It can be used like this:

```
push:
  sources:
    - file: your/path
      params:
        update_descriptions: true
```

Note, this does update all descriptions. This overwrites existing and empty descriptions with new ones. This also updates empty descriptions with existing ones in phraseapp.

The endpoint and parameter is documented here: https://phraseapp.com/docs/api/v2/uploads/#create

We love to hear any feedback as soon as possible.

**Comment by MaxenceMax** [comment]
@sacry-dyn, this one is closed since a long time but is it really work ?   I tried it with the
```
update_descriptions: true
```

but noting change when I'm trying to push locale
thanks !
