### ISSUE TITLE
phraseapp CLI crashes during Xcode build

### ISSUE THREAD

**Issue by tomhamming** [phrase/phraseapp-client#48]
I've got the `phraseapp` CLI client running as part of my Xcode build process to download strings automatically. Running in Xcode 8 on Sierra, once in a while I get a build error "Unexpected signal during runtime execution." It appears to be the phraseapp client. I see this in my build log:

> fatal error: unexpected signal during runtime execution
> [signal 0xb code=0x1 addr=0x42fa57f8 pc=0x2bce65]
> 
> goroutine 38 [running]:
> runtime.throw(0x5ad740, 0x2a)
>   /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82047e600 sp=0xc82047e5e8
> runtime.sigpanic()
>   /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82047e650 sp=0xc82047e600
> runtime/internal/atomic.Load64(0x42fa57f8, 0x42fa57fc6c1f)
>   /usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0xc82047e658 sp=0xc82047e650
> runtime.lfstackpop(0x77ab88, 0x61ff3)
>   /usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0xc82047e690 sp=0xc82047e658
> runtime.getempty(0x67, 0x0)
>   /usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0xc82047e6c0 sp=0xc82047e690
> runtime.(_gcWork).init(0xc820041c20)
>   /usr/local/go/src/runtime/mgcwork.go:100 +0x53 fp=0xc82047e6d8 sp=0xc82047e6c0
> runtime.(_gcWork).tryGet(0xc820041c20, 0x1)
>   /usr/local/go/src/runtime/mgcwork.go:141 +0x38 fp=0xc82047e708 sp=0xc82047e6d8
> runtime.gcDrain(0xc820041c20, 0x5)
>   /usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc82047e740 sp=0xc82047e708
> runtime.gcBgMarkWorker(0xc820040a00)
>   /usr/local/go/src/runtime/mgc.go:1435 +0x583 fp=0xc82047e7b8 sp=0xc82047e740
> runtime.goexit()
>   /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82047e7c0 sp=0xc82047e7b8
> created by runtime.gcBgMarkStartWorkers
>   /usr/local/go/src/runtime/mgc.go:1330 +0x92
> 
> goroutine 1 [select]:
> net/http.(_Transport).getConn(0xc820136000, 0xc82013e0e0, 0x0, 0xc820214080, 0x5, 0xc82020be00, 0x15, 0x0, 0x0, 0x0)
>   /usr/local/go/src/net/http/transport.go:711 +0x4ef
> net/http.(_Transport).RoundTrip(0xc820136000, 0xc82013e0e0, 0xc820136000, 0x0, 0x0)
>   /usr/local/go/src/net/http/transport.go:311 +0x7e9
> net/http.send(0xc82013e0e0, 0x8bf500, 0xc820136000, 0x0, 0x0, 0x0, 0xc820214180, 0x0, 0x0)
>   /usr/local/go/src/net/http/client.go:260 +0x6b7
> net/http.(_Client).send(0xc820210640, 0xc82013e0e0, 0x0, 0x0, 0x0, 0xc8200ecbe0, 0x0, 0x0)
>   /usr/local/go/src/net/http/client.go:155 +0x185
> net/http.(_Client).doFollowingRedirects(0xc820210640, 0xc82013e0e0, 0x5ed1e0, 0x0, 0x0, 0x0)
>   /usr/local/go/src/net/http/client.go:475 +0x8a4
> net/http.(_Client).Do(0xc820210640, 0xc82013e0e0, 0x0, 0x0, 0x0)
>   /usr/local/go/src/net/http/client.go:188 +0xff
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp.(_Client).send(0xc820210640, 0xc82013e0e0, 0xc8, 0x5696c0, 0x0, 0x0)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp/client.go:196 +0x551
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp.(_Client).sendRequest(0xc820210640, 0x51a0c0, 0x3, 0xc8201ffbc0, 0x5f, 0x5696c0, 0x10, 0x8c86e0, 0xc820212770, 0xc8, ...)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp/client.go:163 +0x74f
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp.(_Client).LocaleDownload.func1(0x7fff5fbf9e52, 0x20, 0x7fff5fbf9e73, 0x20, 0xc8200e85e0, 0xc820210640, 0xc82006dc58, 0x0, 0x0)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp/lib.go:2721 +0x3fc
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp.(_Client).LocaleDownload(0xc820210640, 0x7fff5fbf9e52, 0x20, 0x7fff5fbf9e73, 0x20, 0xc820198428, 0x0, 0x0, 0x0, 0x0, ...)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/phrase/phraseapp-go/phraseapp/lib.go:2712 +0xfe
> main.(_LocaleDownload).Run(0xc820198420, 0x0, 0x0)
>   /go/src/github.com/phrase/phraseapp-client/router.go:1752 +0xe8
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/dynport/dgtk/cli.(_Router).Run(0xc8200a3300, 0xc8200ea030, 0x8, 0x8, 0x0, 0x0)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/dynport/dgtk/cli/router.go:54 +0x26c
> github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/dynport/dgtk/cli.(_Router).RunWithArgs(0xc8200a3300, 0x0, 0x0)
>   /go/src/github.com/phrase/phraseapp-client/Godeps/_workspace/src/github.com/dynport/dgtk/cli/router.go:60 +0x7f
> main.Run()
>   /go/src/github.com/phrase/phraseapp-client/main.go:45 +0x22a
> main.main()
>   /go/src/github.com/phrase/phraseapp-client/main.go:13 +0x14
> 
> goroutine 19 [syscall]:
> os/signal.signal_recv(0x0)
>   /usr/local/go/src/runtime/sigqueue.go:116 +0x132
> os/signal.loop()
>   /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
> created by os/signal.init.1
>   /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
> 
> goroutine 20 [chan receive]:
> net/http.(_Transport).dialConn(0xc820136000, 0x0, 0xc820214080, 0x5, 0xc82020be00, 0x15, 0x0, 0x0, 0x0)
>   /usr/local/go/src/net/http/transport.go:834 +0x9c2
> net/http.(_Transport).getConn.func4(0xc820136000, 0x0, 0xc820214080, 0x5, 0xc82020be00, 0x15, 0xc8201ffc20)
>   /usr/local/go/src/net/http/transport.go:706 +0x66
> created by net/http.(*Transport).getConn
>   /usr/local/go/src/net/http/transport.go:708 +0x262
> 
> goroutine 25 [runnable]:
> reflect.Value.Index(0x3d5360, 0xc8204b8760, 0x97, 0x1, 0x4e, 0x305, 0x0)
>   /usr/local/go/src/reflect/value.go:830
> encoding/asn1.parseSequenceOf(0xc8204c20a0, 0x4e, 0x305, 0x8bb028, 0x3d5360, 0x8bb028, 0x3d53e0, 0x3d5360, 0xc8204b8760, 0x97, ...)
>   /usr/local/go/src/encoding/asn1/asn1.go:558 +0x3d5
> encoding/asn1.parseField(0x3d5360, 0xc8204b8740, 0x197, 0xc8204c209e, 0x50, 0x307, 0x0, 0x0, 0x0, 0x0, ...)
>   /usr/local/go/src/encoding/asn1/asn1.go:867 +0x2752
> encoding/asn1.UnmarshalWithParams(0xc8204c209e, 0x50, 0x307, 0x3b2d60, 0xc8204b8740, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>   /usr/local/go/src/encoding/asn1/asn1.go:990 +0x16e
> encoding/asn1.Unmarshal(0xc8204c209e, 0x50, 0x307, 0x3b2d60, 0xc8204b8740, 0x0, 0x0, 0x0, 0x0, 0x0)
>   /usr/local/go/src/encoding/asn1/asn1.go:983 +0x8f
> crypto/x509.parseCertificate(0xc8204c4000, 0x3a5, 0x0, 0x0)
>   /usr/local/go/src/crypto/x509/x509.go:948 +0x46b
> crypto/x509.ParseCertificate(0xc8204c2000, 0x3a5, 0x3a5, 0xb, 0x0, 0x0)
>   /usr/local/go/src/crypto/x509/x509.go:1195 +0x19e
> crypto/x509.(_CertPool).AppendCertsFromPEM(0xc820248300, 0xc82031a5f2, 0x2a65b, 0x6980e, 0xc820248201)
>   /usr/local/go/src/crypto/x509/cert_pool.go:96 +0x11d
> crypto/x509.execSecurityRoots(0x2bb6b5, 0x0, 0x0)
>   /usr/local/go/src/crypto/x509/root_darwin.go:23 +0x23e
> crypto/x509.initSystemRoots()
>   /usr/local/go/src/crypto/x509/root_nocgo_darwin.go:10 +0x18
> sync.(_Once).Do(0x797b28, 0x5ecc38)
>   /usr/local/go/src/sync/once.go:44 +0xe4
> crypto/x509.systemRootsPool(0xc820268e90)
>   /usr/local/go/src/crypto/x509/root.go:15 +0x2f
> crypto/x509.(_Certificate).Verify(0xc820100d80, 0xc82020be00, 0x11, 0xc820222d20, 0x0, 0xecf74c402, 0x36c5dfc7, 0x77a6e0, 0x0, 0x0, ...)
>   /usr/local/go/src/crypto/x509/verify.go:241 +0x1de
> crypto/tls.(_clientHandshakeState).doFullHandshake(0xc820397e38, 0x0, 0x0)
>   /usr/local/go/src/crypto/tls/handshake_client.go:278 +0x6e9
> crypto/tls.(_Conn).clientHandshake(0xc82025a000, 0x0, 0x0)
>   /usr/local/go/src/crypto/tls/handshake_client.go:213 +0x1737
> crypto/tls.(_Conn).Handshake(0xc82025a000, 0x0, 0x0)
>   /usr/local/go/src/crypto/tls/conn.go:1033 +0xec
> net/http.(_Transport).dialConn.func3(0xc82025a000, 0xc820210a00, 0xc820220120)
>   /usr/local/go/src/net/http/transport.go:828 +0x21
> created by net/http.(_Transport).dialConn
>   /usr/local/go/src/net/http/transport.go:833 +0x986

**Comment by sacry-dyn** [comment]
Hey,

thank you for reaching out. We will look into it.

**Comment by sacry-dyn** [comment]
@tomhamming do you have anything other to go on? It looks like from the stacktrace that we receive some kind of exit code from unix: 

```
os/signal.signal_recv(0x0)
/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

and that it is raised

```
runtime.throw(0x5ad740, 0x2a)
/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82047e600 sp=0xc82047e5e8
runtime.sigpanic()
/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82047e650 sp=0xc82047e600
``` 

The other routines work as expected and do not raise anything currently. We would need to get a much more detailed picture on those events, e.g. what happens on the OS/server when the client crashes.

**Comment by tomhamming** [comment]
@sacry-dyn I've copied all the build output that looks relevant into this issue. What else should I look for / what kinds of things do you think could be relevant?

I do also see this line in the log, which I don't think I saw before...

 > ERROR: Get https://api.phraseapp.com/v2/projects/8a90ca4d2e7caa5191787b9ad7778b66/locales/827e14b3bee7a8b2ef2f2d790d607869/download: x509: certificate has expired or is not yet valid

**Comment by sacry-dyn** [comment]
Hi,

this is an error that normally comes up if SSL certificates expire or invalid (often invalid root CAs). If this is something that does not concern you, you are able to set an ENV variable (documented here https://phraseapp.com/docs/developers/cli/usage) to

```
export PHRASEAPP_INSECURE_SKIP_VERIFY=true
```

**Comment by sacry-dyn** [comment]
@tomhamming this could be an issue with Xcode 8 on Sierra. We rebuild the client with the newest go 1.7.1 version in https://github.com/phrase/phraseapp-client/releases/tag/1.2.2 it was reported that the unexpected signal issue occurred on Sierra. Maybe this will help you.

**Comment by tomhamming** [comment]
@sacry-dyn cool. I've updated my phraseapp CLI from Homebrew to 1.2.2. I'll let you know if I see further issues.

**Comment by sacry-dyn** [comment]
will close this for now. If anything pops up feel free to reopen.
