### ISSUE TITLE
Feature Request: Add support for <locale_code> placeholder in locale_id parameter

### ISSUE THREAD

**Issue by rubenvdb** [phrase/phraseapp-client#5]
When mapping custom locales on different language files (e.g. when we decide to map app_nl-BE to our ios app localizable.strings file and iwatch_nl-BE to the watch extension's strings file), it would be nice to be able to write the .phraseapp.yml file like this:

    - file: path/to/app/SupportingFiles/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: app_<locale_code>
    - file: path/to/iwatch/SupportingFiles/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: iwatch_<locale_code>

instead of having to write a different target entry for each additional locale/file that is supported in the project.

**Comment by sacry-dyn** [comment]
Hi @rubenvdb. Could you elaborate on how this will not work with e.g the <locale_name> or <locale_code> described here:

http://docs.phraseapp.com/guides/working-with-phraseapp/command-line-client/

Is it the iwatch_ and app_ that you are missing? How about:

<pre><code>
- file: path/to/app/SupportingFiles/app_&lt;locale_code&gt;.lproj/Localizable.strings
  params:
    file_format: strings
- file: path/to/iwatch/SupportingFiles/iwatch_&lt;locale_code&gt;.lproj/Localizable.strings
  params:
    file_format: strings
</code></pre>

Regards,
Matthias

**Comment by rubenvdb** [comment]
Hi @sacry-dyn,

The thing we're trying to accomplish is this:
We often have a project codebase that has different 'flavors'. Such an app can be built with a build flag that switches between different brands / assets / API endpoints etc. One of the customizable things is the strings file. 
An example:
An app can be built for the Belgian and Dutch market. The Belgian app should support nl-BE, fr-BE and en, and has the Belgian brand, logo and copy and uses the Belgian API endpoint. The Dutch app should only support nl-NL and en, and contain the Dutch assets and endpoints. 

We don't want this to be two phraseapp projects, because that would be a burden when syncing and translating keys. What we do now is adding the locales but prefix them with the "flavor" (e.g. Belgium_nl-BE, Belgium_fr-BE, Belgium_en, Holland_nl-NL, Holland_en). These locales should be synchronized to different strings files, like this:

    - file: BelgianApp/SupportingFiles/en.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Belgium_en
    - file: BelgianApp/SupportingFiles/nl-BE.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Belgium_nl-BE
    - file: BelgianApp/SupportingFiles/fr-BE.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Belgium_fr-BE
    - file: DutchApp/SupportingFiles/en.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Holland_en
    - file: DutchApp/SupportingFiles/nl-NL.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Holland_nl-NL

We have apps with more than 15 flavors each with different locales, which makes the .phraseapp.yml file very verbose and error prone. A nicer way of accomplishing the same syncing behavior would be to be able to write this:

    - file: BelgianApp/SupportingFiles/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Belgium_<locale_code>
    - file: DutchApp/SupportingFiles/<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        locale_id: Holland_<locale_code>

In order to do this, the locale_id param [https://github.com/phrase/phraseapp-client/blob/master/push.go#L268|here] should be checked for containing the <locale_code> placeholder, just like the filename...

**Comment by sacry-dyn** [comment]
@rubenvdb thank you for clarification. Seems like a good addition to the configuration. I have opened a pull request which we will review shortly https://github.com/phrase/phraseapp-client/pull/7

**Comment by sacry-dyn** [comment]
Added as of version 0.3.1.beta
