### ISSUE TITLE
Feature request: store defaults in a user-specific phraseapp.yml file

### ISSUE THREAD

**Issue by rubenvdb** [phrase/phraseapp-client#6]
Right now, the user's API key is stored in each project's .phraseapp.yml file. This file is committed into git, after which other developers and a CI build server all use the same API key for that project. This results in all actions to be done in the capacity of the user who ran the init command. Moreover, this key allows access to all projects of that first user, even if another developer doesn't have access to them.
A more convenient way would be to store the user-specific defaults in a user-specific .phraseapp.yml file (for example in the home dir of the user), allowing them to be overridden in the project-specific file. This would allow every user to store its own api key without committing it.

**Comment by fredv** [comment]
Thank you for this suggestion, @rubenvdb. This is something we're planning to include in a future release. The project .phraseapp.yml would only include the project structure and a .phraseapp.yml in $HOME or $HOME/.config include the user credentials.

**Comment by fredv** [comment]
@rubenvdb have you tried specifying the access-token as argument to phraseapp push/pull ? This should work, so that you can remove it from the shared .phraseapp.yml

**Comment by sacry-dyn** [comment]
@rubenvdb this was not possible as of now. It is fixed and is already in master. Should be out with the next release of the binary. As for the feature request to have a default to look up user specific options is certainly possible but adds another layer of complexity. Is the approach to explicitly set the token via --token possible for you?

**Comment by rubenvdb** [comment]
It is definitely a good solution on our build server, where we can override the developers' access tokens committed in git. For devs however, it adds the additional complexity to always have to add the access token (which is not easy to remember), and to have to manually remove them for security purposes. Therefore, I'd like to keep this feature request open, as storing credentials in a user-specific location seems like best solution for the problem here.

**Comment by sacry-dyn** [comment]
@rubenvdb another possible solution: how about setting an env variable for your auth token?

**Comment by rubenvdb** [comment]
Sounds like a good solution to me!

**Comment by sacry-dyn** [comment]
@rubenvdb addressed this issue in the latest binary release. The order of precedence is as follows: token via command-line > env token > default token in your config.

https://github.com/phrase/phraseapp-client/releases/tag/0.3.4.beta
