### ISSUE TITLE
Runtime Error with release 1.4.0

### ISSUE THREAD

**Issue by lborie** [phrase/phraseapp-client#75]
Hello,

Since the release 1.4.0 (everything was OK with 1.3.0), we have a _Runtime Error_ when we use **phraseapp_linux_amd64** binary.

Here's the exact message : 

> ERROR: This should not have happened: runtime error: invalid memory address or nil pointer dereference - Contact support: support@phraseapp.com

Development environment : 

> CentOS release 6.8 (Final)
> Kernel 2.6.32-642.6.1.el6.x86_64

Thank you !

**Comment by sacry-dyn** [comment]
@lborie thank you for reaching out we will look into it.

**Comment by sacry-dyn** [comment]
@lborie Could you also show us your configuration file? (without any ids). Does this error come up in general or just with certain commands?

**Comment by lborie** [comment]
I can share you my .phraseapp file, but this is a general error. If I launch only the binary, without any parameter, it will display this message too.

**Comment by sacry-dyn** [comment]
@lborie okay. It might be better if you send us your configuration via support at support@phraseapp.com or the form https://phraseapp.com/contact . Credentials and or ids should never be published.

**Comment by tobstarr** [comment]
@lborie I just downloaded that very version and tested it locally (with fedora 25 and 4.9.3-200.fc25.x86_64) and do not see your issue.

I would also guess that this is related to your config file (the config file in your current directory is parsed automatically even without you providing anything).

Can you verify if you also run into that issue when you run the cli tool from e.g. `/tmp`?

**Comment by lborie** [comment]
I will send you an email with my conf.
**BUT** I have also this issue when I run from a folder without any .phraseapp.yml, and everything was fine with 1.3.0

**Comment by lborie** [comment]
A last comment, if it can help : 
All the team is behind an http proxy, and I can't test without it.

**Comment by tobstarr** [comment]
@lborie I created a specific version of the client which prints out more debug information and uploaded it to https://phraseapp-client-releases.s3-eu-west-1.amazonaws.com/debug/phraseapp-panic-test

You could download that, then `chmod a+x phraseapp-panic-test` and run the command again.

I also pushed the changes to a branch `https://github.com/phrase/phraseapp-client/tree/panic-test` from which you could also just build the client yourself (in case you have a policy to not trust unsigned binaries). Only thing you need is a up to date version of go installed and then you could just build via `go install .`

**Comment by tobstarr** [comment]
@lborie the output should not contain any sensitive information so I would ask you to just paste it here. Thank you very much!

**Comment by sacry-dyn** [comment]
@lborie have you had the time to send us your configuration? We tried a couple of false or bad configurations on our Linux systems and they do not (at least in general) seem to break. It would be nice to know what the problem with your specific configuration was, to get a clue on what went wrong.

**Comment by sacry-dyn** [comment]
@lborie If there are any updates on this or further help is required, please reopen this issue.
