### ISSUE TITLE
how to separate access token

### ISSUE THREAD

**Issue by dimalinux** [phrase/phraseapp-client#84]
The .phraseapp.yml files can get quite complicated, so I'd like to put them in source control, but having the access token in them prevents me from doing so.  Making developers pass the access token on the command line is also cumbersome.  Could we get a way to specify the access token separate from the project specific .phraseapp.yml  files?  (e.g. From a separate file in user's home directory or an environment variable.)

**Comment by docstun** [comment]
You should be able to set this via the `PHRASEAPP_ACCESS_TOKEN` env variable as documented here: https://phraseapp.com/docs/developers/cli/usage/#authentication-using-access-token

Does that do the trick?

**Comment by dimalinux** [comment]
That worked great.  Thank you!  Sorry for missing that in the manual!
