### ISSUE TITLE
phraseapp cli client behind proxy

### ISSUE THREAD

**Issue by nexeck** [phrase/phraseapp-client#86]
I am not able to use the phraseapp client behind a proxy:

```
uname -a
Linux ghost 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

phraseapp version: 1.4.1
```

```
echo $HTTPS_PROXY
http://localhost:3128
```

```
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 3
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
bind(4, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
socket(PF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.1.1")}, 16) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(35781), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
getpeername(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.1.1")}, [16]) = 0
getsockopt(3, SOL_SOCKET, SO_ERROR, [110], [4]) = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("192.30.253.112")}, 16) = -1 EINPROGRESS (Operation now in progress)
getsockopt(3, SOL_SOCKET, SO_ERROR, [110], [4]) = 0
ERROR: dial tcp 192.30.253.113:443: getsockopt: connection timed out
```

It looks like the app is ignoring the proxy and just tries to connect directly to: 192.30.253.112:443

**Comment by tobstarr** [comment]
@nexeck we are only using the `HTTPS_PROXY` env variable if you also provide `PHRASEAPP_INSECURE_SKIP_VERIFY=true` (see https://github.com/phrase/phraseapp-client/blob/7a3f83980a97c44ad447001a0a0ff1bee344d6bd/client.go#L18-L20). In that case your connection should go through the configured proxy but `the server's TLS certificate chain is not verified!`. That means you would be vulnerable to a man-in-the-middle attack.

**Comment by nexeck** [comment]
@tobstarr The HTTPS_PROXY env variable is also set:

```
http_proxy="http://localhost:3128"
HTTP_PROXY="http://localhost:3128"
https_proxy="http://localhost:3128"
HTTPS_PROXY="http://localhost:3128"
ftp_proxy="http://localhost:3128"
FTP_PROXY="http://localhost:3128"
```

**Comment by dlein** [comment]
For the Windows client behind the same proxy I have to wait about 40 s each for pulling and pushing. There is an error message, but it works anyway. Maybe that helps for debugging the linux issue?

```
C:\Users\xxx>phraseapp pull
ERROR: dial tcp 192.30.253.112:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Downloaded de to messages_de.properties
Downloaded en to messages_en.properties
Downloaded nl to messages_nl.properties

C:\Users\xxx>phraseapp push
ERROR: dial tcp 192.30.253.112:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Uploading messages_de.properties... done!
Check upload xxx for information about processing results.
Uploading messages_en.properties... done!
Check upload xxx for information about processing results.
Uploading messages_nl.properties... done!
Check upload xxx for information about processing results.
```

**Comment by tobstarr** [comment]
@nexeck what are you using as a proxy server? will try to setup a proxy locally to debug the issue myself.

**Comment by nexeck** [comment]
@tobstarr locally i am using: squid > 3.5.12-1ubuntu7.3

squid config:
```
# This file managed by Salt , do not edit by hand!!
# Squid normally listens to port 3128
http_port 3128

# acl port rules

# acl src rules
acl localhost_src src 127.0.0.0/8
acl localhost_src src ::1/128

acl localnet_src src 10.0.0.0/8
acl localnet_src src 172.16.0.0/12
acl localnet_src src 192.168.0.0/16
acl localnet_src src fc00::/7
acl localnet_src src fe80::/10

acl docker_src src 172.16.0.0/12


# acl dst rules
acl localhost_dst dst 127.0.0.0/8
acl localhost_dst dst ::1/128

acl localnet_dst dst 10.0.0.0/8
acl localnet_dst dst 172.16.0.0/12
acl localnet_dst dst 192.168.0.0/16
acl localnet_dst dst fc00::/7
acl localnet_dst dst fe80::/10


# acl dstdomain rules

# http_access rules
http_access allow localhost_src
http_access allow docker_src


# And finally deny all other access to this proxy
http_access deny all

# cache rules
cache deny all


# cache_peer rules

# always_direct rules
always_direct allow all


# never_direct rules

# Leave coredumps in the first cache dir
coredump_dir /var/spool/squid

# hostname
visible_hostname ghost

# Wait x seconds before termination
shutdown_lifetime 5 seconds

# Extra configuration
```

**Comment by tobstarr** [comment]
@nexeck I am sorry to inform you that I failed to reproduce your issue locally. What I did was this:

* run squid in a docker container using my local network interface: `docker run --net=host --name squid sameersbn/squid`
* monitor the logs of that container: `docker exec squid tail -f /var/log/squid3/access.log`

Then I tested the client doing this:

	export HTTPS_PROXY="http://localhost:3128"
	phraseapp-client formats list -t test

and I could see the requests going through the squid proxy:

	1487750778.737    318 ::1 TCP_MISS/200 7302 CONNECT api.phraseapp.com:443 - HIER_DIRECT/54.76.19.222 -

Using the env variables `http_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` also worked. I also did not have to provide the `PHRASEAPP_INSECURE_SKIP_VERIFY=true` option at all.

Is that proxy picked up by e.g. curl (what do you get when you run e.g. `curl -v -I https://phraseapp.com`)? You should see this in the output:

	* Connected to localhost (::1) port 3128 (#0)
	* Establish HTTP proxy tunnel to phraseapp.com:443

Another thing you could try is listen for traffic using ngrep:

	sudo ngrep port 3128 -d lo -q -l

The output should include something like this

	T ::1:57646 -> ::1:3128 [AP]
	  CONNECT api.phraseapp.com:443 HTTP/1.1..Host: api.phraseapp.com:443..User-Agent: Go-http-client/1.1..

Did you run the client from a directory where there is a .phraseapp.yml file present?

**Comment by nexeck** [comment]
@tobstarr 
Thank you for your feedback.
I have tried the following:

```shell
curl -v -I https://phraseapp.com
```
Result:
```
access.log: 1487841613.228    395 127.0.0.1 TCP_TUNNEL/200 6507 CONNECT phraseapp.com:443 - FIRSTUP_PARENT/10.60.2.23 -


curl -v -I https://phraseapp.com
* Rebuilt URL to: https://phraseapp.com/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3128 (#0)
* Establish HTTP proxy tunnel to phraseapp.com:443
> CONNECT phraseapp.com:443 HTTP/1.1
> Host: phraseapp.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
HTTP/1.1 200 Connection established
< 

* Proxy replied OK to CONNECT request

```

I am going to try to debug this the next days with another System.

**Comment by nexeck** [comment]
I can reproduce your results on another system.
And i can reproduce you results on another network with the "not working system".

Will try again in the corporate network.

**Comment by nexeck** [comment]
@tobstarr 

This is strange.

Given:
- System1: with Docker Squid (Like your Example)
- System2: with local Squid (Corporate System)

Steps i have done:
System1:
- Works with docker squid

System2:
- Does not work with local and docker squid (Corporate Network)
- Move System2 into private Network, works with local and docker squid
- Move System2 back into Corporate Network, works with local squid
- Reboot System2, does not work with local or docker squid

Is there anything the Client caches?
Maybe only one request which does not use the HTTPS_PROXY ENV's?

After one Working Request, i can move the system (withouth rebooting) back into the corporate Network, and it will work.
After one reboot, i cannot use phraseapp again.

**Comment by tobstarr** [comment]
@nexeck we were actually able to locate the issue (the version check was not going through the proxy) and @theSoenke provided a fix I just merged with PR https://github.com/phrase/phraseapp-client/pull/88

This will go into the next release we will probably release in the next days. 

If you want to use the feature before you could just build the client yourself from our master branch. If you already have a docker setup running, the quickest way would be to use

    docker run -t -i -v $(pwd):/go/bin golang:1.8 sh -c "go get -v github.com/phrase/phraseapp-client"

This will build the client in a docker container and place the final binary in your current directory.

**Comment by alexanderwilling** [comment]
fixed in https://github.com/phrase/phraseapp-client/commit/474e4696080de9cad000c22a6ca2c99ccc04bbfc and thus [version 1.4.3](https://github.com/phrase/phraseapp-client/releases/tag/1.4.3)
