### ISSUE TITLE
Params 'tags' seems not working with 'phraseapp push'

### ISSUE THREAD

**Issue by citysite102** [phrase/phraseapp-client#93]
.phraseapp.yml setting as follows:

`push:
    sources: 
    - file: ./Demo/da.lproj/demo.strings
      params:
        file_format: strings
        locale_id: <locale_id>
        tags: Demo___da.lproj___demo.strings
        update_descriptions: true
`

With the above configuration, new key within file demo.strings can be successfully added but the tag won't associate with the new added key.

**Comment by sacry-dyn** [comment]
Hi @citysite102 ,

the configuration looks okay. So the point here is that `update_descriptions: true` only updates the descriptions on the keys (and essentially nothing else). In this case you will need to combine this with `update_translations: true`. The problem with update_translations: true would be that all keys (including old ones that are in the file) will get tagged by  `Demo___da.lproj___demo.strings`.  Would this cause issues with your flow to enable `update_translations: true`?

**Comment by sacry-dyn** [comment]
Hi @citysite102 

we fixed this in our app and you should be able to use `update_descriptions` without the `update_translations` flag while still tagging newly created keys. If anything else comes up or the current state does not work as you thought, feel free to reopen or submit another issue.
