### ISSUE TITLE
Regexp issue on Windows

### ISSUE THREAD

**Issue by tobstarr** [phrase/phraseapp-client#98]
There is an issue when using regexp patterns on windows because the windows path seperator here https://github.com/phrase/phraseapp-client/blob/master/internal/placeholders/placeholders.go#L62 acts as a escape character in the regexp.

**Comment by sacry-dyn** [comment]
This seems to be related https://github.com/phrase/phraseapp-client/issues/94

**Comment by theSoenke** [comment]
Resolved in https://github.com/phrase/phraseapp-client/pull/100
